In [15]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import os

url = 'https://www.ncei.noaa.gov/data/local-climatological-data/access/2021/'



if not os.path.exists('data'):
    os.makedirs('data')
    print('Directory "data" created')

print(f'Waiting response from GET request {url}')
html = requests.get(url).content
soup = BeautifulSoup(html, 'html.parser')
csv_file = soup.find('td', string='2022-02-07 14:03  ').find_previous_sibling('td').text
download_url = requests.get(url+csv_file).content
print(f'Downloading file {csv_file}')
open(f'data/{csv_file}', 'wb').write(download_url)
print(f'File {csv_file} downloaded.')

Waiting response from GET request https://www.ncei.noaa.gov/data/local-climatological-data/access/2021/
Downloading file 01011099999.csv
File 01011099999.csv downloaded.

In [17]:
data_pd = pd.read_csv(f'data/{csv_file}')
filtered_data = data_pd.sort_values(['HourlyDryBulbTemperature'], ascending=False).head(5)
filtered_data

,STATION,DATE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,SOURCE,HourlyAltimeterSetting,HourlyDewPointTemperature,...,BackupDirection,BackupDistance,BackupDistanceUnit,BackupElements,BackupElevation,BackupEquipment,BackupLatitude,BackupLongitude,BackupName,WindEquipmentChangeDate
180,1011099999,2021-08-11T22:00:00,80.066667,31.5,10.0,"KVITOYA, SV",FM-12,4,NaN,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,1011099999,2021-07-16T03:00:00,80.066667,31.5,10.0,"KVITOYA, SV",FM-12,4,NaN,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,1011099999,2021-08-10T14:00:00,80.066667,31.5,10.0,"KVITOYA, SV",FM-12,4,NaN,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,1011099999,2021-08-03T10:00:00,80.066667,31.5,10.0,"KVITOYA, SV",FM-12,4,NaN,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161,1011099999,2021-07-15T20:00:00,80.066667,31.5,10.0,"KVITOYA, SV",FM-12,4,NaN,35.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
filtered_data.to_csv(f'Filter_{csv_file}', index=True)